name: rrad_mfa
description: Flutter package for Multi Factor Authentication.
version: 0.0.1
homepage: "https://rrad.com.bd"

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  http: ^0.13.4

dev_dependencies:
  test: ^1.16.0
